language: python
python:
  - 2.7
  - 3.3
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make build27; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then make build33; fi
script: make test
